apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: default
spec:
   replicas: 3
   image: postgres:15.0
   database:
      size: 256Mi
   backup:
     schedule: "0 */1 * * *"
     pvcName: postgres-backup-pvc
     volumeMount: /var/lib/backup
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret
              key: super_user_password

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret
              key: replication_user_password